### ISSUE TITLE
ERROR in NIBCONV

### ISSUE THREAD

**Issue by spiro-trikaliotis** [rittwage/nibtools#1]
(this is a clone of https://github.com/OpenCBM/nibtools/issues/8, as reported by @0wwafa):

If you convert a d64 into G64 and set the speed to 300 RPM, you get a 296.4 RPM disk!

![image](https://github.com/user-attachments/assets/4930d7d1-89eb-4b2c-bbe1-bd3d9e8861be)

Track 1-17 length should be 200000 / 26 = 7692 = $1E0C bytes.
On real drives the speed is almost 300 and usually creates tracks of 1E04 bytes (1541 II and 1571 have fixed speeds).

1DB2 (see picture) is 7602 (maybe a typo?) and that means 7602 * 26 = 197652; 200000/197652 * 300 = 303.56 RPM!

**Comment by rittwage** [comment]
In this situation, nibconv simply "renders" a D64 file to a G64 using the standard sync and gap lengths. 

It does not add a tail gap to pad out the track to the length you specified, or attempt to "stretch" the sectors with gaps or exta sync to do so. 

It was never intended to do that. What is the use-case?

**Comment by rittwage** [comment]
I have added the padding of D64 data during conversion to the RPM specified.
